### ISSUE TITLE
Fail the node synchronization after config edit using vim editor

### ISSUE THREAD

**Issue by hitobb** [nemfoundation/symbol-testnet-bootstrap#5]
Hi nem foundation,

Please check this behavior.

[issue]

1.
git clone https://github.com/nemfoundation/symbol-testnet-bootstrap.git

2.
cd symbol-testnet-bootstrap/api-harvest-assembly/

3.
docker-compose up --build --detach

4.
At this time,
node synchronization is clearly working

5.
docker-compose down

6.
cd api-node

7.
[point]
Edit friendly_name on config-input.yaml using vim editor
and
Add a space at the end of friendly_name

8.
cd ..

9.
docker-compose up --build --detach

Strangely, this operation succeeds

10.
Unfortunately, nodes are no longer in sync

[What is the problem]

I think the VIM Editor has entered an incorrect line break.
So symbol need to make this code as error.

[docker-compose log (tail)]
```
rest-gateway_1            | (node:26) UnhandledPromiseRejectionWarning: Error: verify failed with 1
rest-gateway_1            |     at Socket.serverSocket.on.on (/app/catapult-sdk/_build/auth/auth.js:72:13)
rest-gateway_1            |     at Socket.emit (events.js:203:15)
rest-gateway_1            |     at Socket.EventEmitter.emit (domain.js:448:20)
rest-gateway_1            |     at TCP._handle.close (net.js:607:12)
rest-gateway_1            | (node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
*******@symbol-testnet:~/symbol-testnet-bootstrap/api-harvest-assembly$ 
```

[OS]
Server: ubuntu 18.04(64bit)
Client: MAC OS standard console (using ssh Client)

---

Thanks,

**Comment by evias** [comment]
> I think the VIM Editor has entered an incorrect line break.
> So symbol need to make this code as error.

This is your Operating System being configured with different line endings than the bootstrap service repository.

You can configure VIM to use the same line endings.

If you still encounter problems after adapting your editor, feel free to re-open this issue :+1:
